---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(feather)
library(survey)
library(ggthemes)
```




```{r}
df <- read_feather("C:/Users/natek/Documents/mpi_exp_df.feather")
```

```{r}
df$mpi_score = df$income_poverty*(1/9) + 
  df$fam_emp *(1/9) + 
  df$health*(1/9) + 
  df$education*(1/9) +
  df$overcrowd*(1/9) +
  df$computer_internet*(1/9) + 
  df$disability*(1/9) +
  df$lang_dep * (1/9) +
  df$hcost_dep * (1/9)

df$mpi_poor = if_else(df$mpi_score > .32, 1, 0)
```

```{r}
svy_df <- svydesign(ids = ~1, weights = ~PERWT, data = df)
state_year_mean <- svyby(~mpi_poor + income_poverty+fam_emp+health+disability+education + overcrowd+hcost_dep+computer_internet+lang_dep, ~STATEFIP + YEAR, design = svy_df, svymean)
```

# Intensity of deprivation among only the MPI poor
```{r}
svy_df_p <- subset(svy_df, mpi_poor == 1)
rm(svy_df)
state_year_intensity <- svyby(~mpi_score, ~STATEFIP + YEAR, design = svy_df_p, svymean)
rm(svy_df_p)
```

```{r}
state_year_mean <- state_year_mean %>% rename(headcount = mpi_poor, inc_inc = income_poverty, inc_emp = fam_emp, inc_health = health, inc_dis = disability, inc_edu = education, inc_crowd = overcrowd, inc_house = hcost_dep, inc_int = computer_internet, inc_lng = lang_dep, se_headcount = se.mpi_poor, se_inc_inc = se.income_poverty, se_inc_emp = se.fam_emp, se_inc_health = se.health, se_inc_dis = se.disability, se_inc_edu = se.education, se_inc_crowd = se.overcrowd, se_inc_house = se.hcost_dep, se_inc_int = se.computer_internet, se_inc_lng = se.lang_dep)
state_intensity <- state_year_intensity %>% rename(intensity = mpi_score, int_se = se)
state_df <- full_join(state_year_mean, state_intensity, by = c("STATEFIP", "YEAR"))
state_df$adj_hc <- state_df$headcount * state_df$intensity
rm(state_year_mean, state_year_intensity)
```

Censored data
```{r}
cen_df <- df
cen_df[cen_df$mpi_poor == 0, 12:20] <- 0
cen_df <- svydesign(ids = ~1, weights = ~PERWT, data = cen_df)
rm(df)
```

```{r}
cen_hc <- svyby(~income_poverty+fam_emp+health+disability+education + overcrowd+hcost_dep+computer_internet+lang_dep, ~STATEFIP + YEAR, design = cen_df, svymean)
```

```{r}
cen_hc <- cen_hc %>%
  rename(cen_inc = income_poverty, cen_emp = fam_emp, cen_health = health, cen_disability = disability, cen_edu = education, cen_crowd = overcrowd, cen_house = hcost_dep, cen_int = computer_internet, cen_lng = lang_dep, se_cen_inc = se.income_poverty, se_cen_emp = se.fam_emp, se_cen_health = se.health, se_cen_disability = se.disability, se_cen_edu = se.education, se_cen_crowd = se.overcrowd, se_cen_house = se.hcost_dep, se_cen_int = se.computer_internet, se_cen_lng = se.lang_dep)
```


```{r}
state_df <- full_join(state_df, cen_hc, by = c("STATEFIP", "YEAR"))
state_df <- state_df %>%
  mutate(per_con_inc = (cen_inc/adj_hc) * (1/9),
         per_con_emp = (cen_emp/adj_hc) * (1/9),
         per_con_hlth = (cen_health/adj_hc) * (1/9),
         per_con_dis = (cen_disability/adj_hc) * (1/9),
         per_con_edu = (cen_edu/adj_hc) * (1/9),
         per_con_crowd = (cen_crowd/adj_hc) * (1/9),
         per_con_hcost = (cen_house / adj_hc) * (1/9),
         per_con_int = (cen_int / adj_hc) * (1/9),
         per_con_lng = (cen_lng / adj_hc) * (1/9), 
         per_con_dim_edu = per_con_edu + per_con_int + per_con_lng,
         per_con_dim_inc = per_con_inc + per_con_emp + per_con_hcost,
         per_con_dim_hlth = per_con_hlth + per_con_dis + per_con_crowd)
```

```{r}
state_df <- state_df %>%
  group_by(YEAR) %>%
  arrange(adj_hc) %>%
  mutate(adj_hc_rank = 1:51)%>%
  arrange(headcount) %>%
  mutate(headcount_rank = 1:51) %>%
  arrange(per_con_inc) %>%
  mutate(per_con_inc_rank = 1:51) %>%
  arrange(per_con_emp) %>%
  mutate(per_con_emp_rank = 1:51) %>%
  arrange(per_con_hlth) %>%
  mutate(per_con_hlth_rank = 1:51) %>%
  arrange(per_con_dis) %>%
  mutate(per_con_dis_rank = 1:51) %>%
  arrange(per_con_edu) %>%
  mutate(per_con_edu_rank = 1:51) %>%
  arrange(per_con_crowd) %>%
  mutate(per_con_crowd_rank = 1:51) %>%
  arrange(per_con_hcost) %>%
  mutate(per_con_hcost_rank = 1:51) %>%
  arrange(per_con_int) %>%
  mutate(per_con_int_rank = 1:51) %>%
  arrange(per_con_lng) %>%
  mutate(per_con_lng_rank = 1:51) %>%
  ungroup()
```

```{r}
write_csv(state_df, "state_year_mpi.csv")
```
