---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(geofacet)
library(ggthemes)
library(rgdal)
library(tmap)
```

```{r}
state_df <- read_csv("state_year_mpi.csv")
```

```{r}
state_fips <- read_csv("C:/Users/natek/Google Drive/Dissertation/state names and medicaid.csv")
```

```{r}
state_df <- left_join(state_df, state_fips, by = "STATEFIP")
```

```{r}
state_md <- state_df %>%
  group_by(YEAR, Medicaid_Expansion) %>%
  summarize(adj_hc = mean(adj_hc),
            per_con_hlth = mean(per_con_hlth))

p <- ggplot(data = state_md, aes(YEAR, adj_hc, group = Medicaid_Expansion)) + geom_line()
p2 <- ggplot(data = state_md, aes(YEAR, per_con_hlth * 100, group = Medicaid_Expansion, linetype = Medicaid_Expansion)) + geom_line()
p2 <- p2 + labs(title = "Percent Contribution of Health Insurance over time", x = "Year", y = "Percent Contribution of Health Insurance") + theme_tufte()
p2 <- p2 + scale_linetype_discrete(name = "Medicaid\nExpansion", breaks = c("1", "0"), labels = c("Yes", "No"))

```

```{r}
state_df$Medicaid_Expansion <- as.factor(state_df$Medicaid_Expansion)
state_df1315 <- state_df %>% filter(YEAR != 2016)
ddreg1 <- lm(adj_hc~YEAR*Medicaid_Expansion, data = state_df1315)
summary(ddreg1)
ddreg2 <- lm(per_con_hlth~YEAR*Medicaid_Expansion, data = state_df1315)
summary(ddreg2)
```



```{r}
p <- ggplot(state_df, aes(year, adj_hc *100)) +
  geom_line() +
  scale_x_continuous(labels = function(x) paste0("'", substr(x, 3, 4))) +
  scale_y_continuous(breaks = c(4, 7, 10)) +
  #theme(axis.text = element_blank(), axis.ticks = element_blank()) +
  facet_geo(~st_abr) +
  labs(title = "Multidimensional Poverty in U.S. states from 2013 to 2016", x = "Year", y = "Adjusted Headcount",
       caption = "Source: Author's analysis of American Community Survey data via IPUMS")
```

# Percent contribution of health insurance
```{r}
p <- ggplot(state_df, aes(YEAR, per_con_hlth *100, linetype = as.factor(Medicaid_Expansion))) +
  geom_line() + guides(linetype = FALSE) +
  scale_x_continuous(labels = function(x) paste0("'", substr(x, 3, 4))) +
  #scale_y_continuous(breaks = c(4, 7, 10)) +
  #theme(axis.text = element_blank(), axis.ticks = element_blank()) +
  facet_geo(~st_abr) +
  labs(title = "Percent Contribution of Health Insurance to MPI in U.S. states from 2013 to 2016", x = "Year", y = "Adjusted Headcount",
       caption = "Dashed lines represent states that expanded Medicaid \nSource: Author's analysis of American Community Survey data via IPUMS")
```


# state bar chart
```{r}
bplot_df <- state_df %>%
  filter(YEAR == 2016) %>%
  select(st_abr, per_con_dim_edu, per_con_dim_hlth, per_con_dim_inc) %>%
  mutate(Health = per_con_dim_hlth * 100, Education = per_con_dim_edu*100, Economic = per_con_dim_inc * 100) %>%
  gather(key = "Dimension", value = "value", Health, Education, Economic)

p <- ggplot(bplot_df, aes(Dimension, value, fill = Dimension)) +
  guides(fill = FALSE) +
  geom_col() +
  coord_flip() + 
  facet_geo(~st_abr) +
  labs(title = "Percent Contribution by Dimension, 2016", x = "Dimension", y = "Percent Contribution",
       caption = "Source: Author's analysis of American Community Survey data via IPUMS")
```



# choroplethr map
```{r}

region <- tolower(state_df$State[state_df$year == 2016])
value <- state_df$adj_hc[state_df$year == 2016]
value <- round(value * 100, 1)
plt_map_df <- data.frame(region, value)
plt_map <- state_choropleth(plt_map_df)
plt_map <- plt_map + labs(title = "Adjusted Headcount, 2016") + theme(plot.title = element_text(hjust = 0.5))
```

#calculate correlation coefficient for state income poverty. 
```{r}
state_df_16 <- state_df %>% filter(YEAR == 2016)
cor(state_df$adj_hc, state_df$inc_inc)
state_df_16 <- state_df_16 %>% arrange(adj_hc)
```

#Plot of income poverty v. mpi poverty
```{r}
p <- ggplot(state_df_16, aes(x = inc_inc*100, y = adj_hc * 100)) + geom_label(aes(label = st_abr))+ geom_smooth(method = "lm", se = FALSE)
p <- p + labs(title = "Income Poverty and Adjusted Headcount, 2016 ", y = "Adjusted Headcount", x = "Income Poverty") + theme_tufte()
```

## Kentucky analysis

```{r}
ky_shp <- readOGR("C:/Users/natek/Google Drive/Dissertation/cb_2016_21_puma10_500k", layer = "cb_2016_21_puma10_500k", GDAL1_integer64_policy = TRUE) 
#plot(ky_shp)
```

```{r}
df <- read_feather("C:/Users/natek/Documents/mpi_exp_df.feather")
df_ky_16 <- df %>% filter(STATEFIP == 21 & YEAR == 2016)
```

```{r}
df_ky_16$mpi_score = df_ky_16$income_poverty*(1/9) + 
  df_ky_16$fam_emp *(1/9) + 
  df_ky_16$health*(1/9) + 
  df_ky_16$education*(1/9) +
  df_ky_16$overcrowd*(1/9) +
  df_ky_16$computer_internet*(1/9) + 
  df_ky_16$disability*(1/9) +
  df_ky_16$lang_dep * (1/9) +
  df_ky_16$hcost_dep * (1/9)

df_ky_16$mpi_poor = if_else(df_ky_16$mpi_score > .32, 1, 0)
```


```{r}
ky_svy <- svydesign(ids = ~1, weights = ~PERWT, data = df_ky_16)
ky_16_mean <- svyby(~mpi_poor + income_poverty+fam_emp+health+disability+education + overcrowd+hcost_dep+computer_internet+lang_dep, ~PUMA, design = ky_svy, svymean)
```


# Intensity of deprivation among only the MPI poor
```{r}
ky_svy_p <- subset(ky_svy, mpi_poor == 1)
ky_16_intensity <- svyby(~mpi_score, ~PUMA, design = ky_svy_p, svymean)
```

```{r}
ky_16_mean <- ky_16_mean %>% rename(headcount = mpi_poor, inc_inc = income_poverty, inc_emp = fam_emp, inc_health = health, inc_dis = disability, inc_edu = education, inc_crowd = overcrowd, inc_house = hcost_dep, inc_int = computer_internet, inc_lng = lang_dep, se_headcount = se.mpi_poor, se_inc_inc = se.income_poverty, se_inc_emp = se.fam_emp, se_inc_health = se.health, se_inc_dis = se.disability, se_inc_edu = se.education, se_inc_crowd = se.overcrowd, se_inc_house = se.hcost_dep, se_inc_int = se.computer_internet, se_inc_lng = se.lang_dep)

ky_16_intensity <- ky_16_intensity %>% rename(intensity = mpi_score, int_se = se)

ky_df <- full_join(ky_16_mean, ky_16_intensity, by = c("PUMA"))

ky_df$adj_hc <- ky_df$headcount * ky_df$intensity

```

Censored data
```{r}
cen_df <- df_ky_16
cen_df[cen_df$mpi_poor == 0, 12:20] <- 0
cen_df <- svydesign(ids = ~1, weights = ~PERWT, data = cen_df)
```

```{r}
cen_hc <- svyby(~income_poverty+fam_emp+health+disability+education + overcrowd+hcost_dep+computer_internet+lang_dep, ~PUMA, design = cen_df, svymean)
```

```{r}
cen_hc <- cen_hc %>%
  rename(cen_inc = income_poverty, cen_emp = fam_emp, cen_health = health, cen_disability = disability, cen_edu = education, cen_crowd = overcrowd, cen_house = hcost_dep, cen_int = computer_internet, cen_lng = lang_dep, se_cen_inc = se.income_poverty, se_cen_emp = se.fam_emp, se_cen_health = se.health, se_cen_disability = se.disability, se_cen_edu = se.education, se_cen_crowd = se.overcrowd, se_cen_house = se.hcost_dep, se_cen_int = se.computer_internet, se_cen_lng = se.lang_dep)
```


```{r}
ky_df <- full_join(ky_df, cen_hc, by = c("PUMA"))
ky_df <- ky_df %>%
  mutate(per_con_inc = (cen_inc/adj_hc) * (1/9),
         per_con_emp = (cen_emp/adj_hc) * (1/9),
         per_con_hlth = (cen_health/adj_hc) * (1/9),
         per_con_dis = (cen_disability/adj_hc) * (1/9),
         per_con_edu = (cen_edu/adj_hc) * (1/9),
         per_con_crowd = (cen_crowd/adj_hc) * (1/9),
         per_con_hcost = (cen_house / adj_hc) * (1/9),
         per_con_int = (cen_int / adj_hc) * (1/9),
         per_con_lng = (cen_lng / adj_hc) * (1/9), 
         per_con_dim_edu = per_con_edu + per_con_int + per_con_lng,
         per_con_dim_inc = per_con_inc + per_con_emp + per_con_hcost,
         per_con_dim_hlth = per_con_hlth + per_con_dis + per_con_crowd)
```

##joining vars to shapefile

```{r}
ky_shp@data$PUMA <- as.numeric(as.character(ky_shp@data$PUMACE10))
ky_shp@data <- full_join(ky_shp@data, ky_df, by = "PUMA")
```

```{r}
ky_shp@data$adj_hc <- ky_shp@data$adj_hc * 100
```

```{r}
ky_shp@data$per_con_hcost <- ky_shp@data$per_con_hcost * 100
ky_shp@data$per_con_int <- ky_shp@data$per_con_int * 100

```


```{r}
ky_map <- tm_shape(ky_shp) +
  tm_polygons("adj_hc", style="quantile", title="Adjusted Headcount", palette = "Blues")
ky_house <- tm_shape(ky_shp) +
  tm_polygons("per_con_hcost", style="quantile", title="Housing Cost Percent Contribution", palette = "Blues")
ky_int <- tm_shape(ky_shp) +
  tm_polygons("per_con_int", style="quantile", title="Internet Access Percent Contribution", palette = "Blues")
```

## Per con in KY over time

- use facet_wrap?
```{r}
ky_per_con_df <- state_df %>% filter(STATEFIP == 21)
```


